/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_odonoghuelab_molecularcontroltoolkit_KinectConnector */

#ifndef _Included_org_odonoghuelab_molecularcontroltoolkit_KinectSetup2
#define _Included_org_odonoghuelab_molecularcontroltoolkit_KinectSetup2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_odonoghuelab_molecularcontroltoolkit_KinectConnector
 * Method:    registerKinect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_odonoghuelab_molecularcontroltoolkit_KinectConnector_registerKinect
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_org_odonoghuelab_molecularcontroltoolkit_KinectConnector_deregisterKinect
  (JNIEnv *, jobject);




#pragma once

enum AquariaAction
{
	ActionNone,
	ActionReset,
    ActionShow,
    ActionLoad,
	ActionZoom,
	ActionSearch,
	ActionSelectAll,
	ActionSelectUp,
	ActionSelectLigand,
	ActionSelectAllLigands,
	ActionSelectNextLigand,
	ActionSelectProximity,
	ActionSelectResidue,
	ActionSelectChain,
	ActionSelectSubChain,
	ActionDeselect,
	ActionSpin,
	ActionStopSpin,
	ActionSpinCrazy,
	ActionCopy,
	ActionPaste,
	ActionHandsOn,
	ActionHandsOff,
	ActionWakeUp,
	ActionGoToSleep,
	ActionColorDisplacement,
	ActionColorStructure,
	ActionColorSecondaryStructure,
	ActionColorSequenceSimilarity
};

void enableHands(bool enabled);
void zoomNow(int zoom);
void panNow(int x, int y);
void point(float x, float y);
void rotateNow(int rotateX, int rotateY, int rotateZ);
void processSpeech(AquariaAction action);
void processSpeechSearch(LPCWSTR searchTerm);

#ifdef __cplusplus
}
#endif
#endif
